### ISSUE TITLE
Add menu on hover

### ISSUE THREAD

**Issue by rudnitskih** [ArtemChubatyi/home-dsgn#1]
![image](https://user-images.githubusercontent.com/8848858/47775900-b36c8080-dcf9-11e8-830e-53608dc756fd.png)

**Comment by ArtemChubatyi** [comment]
@rudnitskih done
![image](https://user-images.githubusercontent.com/43701381/47844444-2691f780-ddcb-11e8-94ac-93383abcfced.png)
