### ISSUE TITLE
Сделай лого в футере как в макете

### ISSUE THREAD

**Issue by scandy5** [ArtemChubatyi/home-dsgn#10]
у тебя:
![image](https://user-images.githubusercontent.com/41551315/47783063-7fe62200-dd0a-11e8-9142-d9f692ce6b52.png)

в макете:
![image](https://user-images.githubusercontent.com/41551315/47783075-86749980-dd0a-11e8-8f00-74fc2d86a345.png)

**Comment by ArtemChubatyi** [comment]
@scandy5 Done
![image](https://user-images.githubusercontent.com/43701381/47858514-eb0c2300-ddf4-11e8-91a6-f6d3b70d41bd.png)
