### ISSUE TITLE
Иконки социальные лучше вести на примитивные ссылки

### ISSUE THREAD

**Issue by scandy5** [ArtemChubatyi/home-dsgn#11]
Мне такой коммент вот Дима оставлял. К примеру если иконка твиттер, то на https://twitter.com/
![image](https://user-images.githubusercontent.com/41551315/47783182-ba4fbf00-dd0a-11e8-9fbc-986ae22b8525.png)
![image](https://user-images.githubusercontent.com/41551315/47783193-c176cd00-dd0a-11e8-91a1-76fc311316c8.png)

**Comment by ArtemChubatyi** [comment]
@scandy5 done
![image](https://user-images.githubusercontent.com/43701381/47858960-da0fe180-ddf5-11e8-9da0-f4cb996e0429.png)
