### ISSUE TITLE
Поменяй title, а этот "скрытый" японский флаг на фавиконе мне тоже нравится)

### ISSUE THREAD

**Issue by scandy5** [ArtemChubatyi/home-dsgn#12]
![image](https://user-images.githubusercontent.com/41551315/47783303-026ee180-dd0b-11e8-80ec-f84aff5ede4e.png)

**Comment by ArtemChubatyi** [comment]
@scandy5 Done)
![image](https://user-images.githubusercontent.com/43701381/47859204-76d27f00-ddf6-11e8-9f28-e683c5fd78aa.png)
