### ISSUE TITLE
Mess with colors

### ISSUE THREAD

**Issue by rudnitskih** [ArtemChubatyi/home-dsgn#13]
![image](https://user-images.githubusercontent.com/8848858/47914748-60393000-dea9-11e8-8639-0ec4733d63c0.png)

**Comment by rudnitskih** [comment]
border-colors I mean

**Comment by ArtemChubatyi** [comment]
@rudnitskih fixed
![image](https://user-images.githubusercontent.com/43701381/47993984-b9979e00-e0f9-11e8-85c1-76fd89aabd5f.png)
