### ISSUE TITLE
Studio and News blocks consume a lot of space on tablet

### ISSUE THREAD

**Issue by rudnitskih** [ArtemChubatyi/home-dsgn#14]
Try to make colorful blocks horizontal as a solution:

![image](https://user-images.githubusercontent.com/8848858/47914989-274d8b00-deaa-11e8-94e8-ff8919fa2c59.png)

**Comment by ArtemChubatyi** [comment]
@rudnitskih fixed
![image](https://user-images.githubusercontent.com/43701381/47997295-fc5e7380-e103-11e8-9b73-ba03974ab863.png)
