### ISSUE TITLE
Optional: remove unneeded files after will finish adaptive version

### ISSUE THREAD

**Issue by rudnitskih** [ArtemChubatyi/home-dsgn#5]
![image](https://user-images.githubusercontent.com/8848858/47777351-3e9b4580-dcfd-11e8-9bc0-e22666183086.png)

**Comment by ArtemChubatyi** [comment]
@rudnitskih 
You looked in another repository. These are the "Pages"  where I upload sites for viewing.
 
The main repo of this project is clear.
![image](https://user-images.githubusercontent.com/43701381/47853661-19373600-dde8-11e8-8a06-6895c692b6fe.png)
