### ISSUE TITLE
Usually you don't need nagative vertical margins - use absolute instead

### ISSUE THREAD

**Issue by rudnitskih** [ArtemChubatyi/home-dsgn#6]
![image](https://user-images.githubusercontent.com/8848858/47777621-cda85d80-dcfd-11e8-93d6-f3026a9cf7d9.png)

Just set `position: absolute` for `.projects__line`.

**Comment by rudnitskih** [comment]
I am talking about `projects__list`, `projects__title`:

![image](https://user-images.githubusercontent.com/8848858/47914665-1e0fee80-dea9-11e8-88ee-e126484491ca.png)


![image](https://user-images.githubusercontent.com/8848858/47914686-341daf00-dea9-11e8-9533-668299f599a2.png)

**Comment by ArtemChubatyi** [comment]
Fixed

![image](https://user-images.githubusercontent.com/43701381/47996341-da172680-e100-11e8-9bc3-f5b815ffee04.png)
