### ISSUE TITLE
Сьехала иконка

### ISSUE THREAD

**Issue by scandy5** [ArtemChubatyi/home-dsgn#8]
Выровняй как в макете
Макет:
![image](https://user-images.githubusercontent.com/41551315/47782933-1d8d2180-dd0a-11e8-8394-8238fc5c63c2.png)
Твой проект:
![image](https://user-images.githubusercontent.com/41551315/47782943-24b42f80-dd0a-11e8-9f7d-8e7e94a678e7.png)

**Comment by ArtemChubatyi** [comment]
@scandy5 done
![image](https://user-images.githubusercontent.com/43701381/47858058-d8451e80-ddf3-11e8-9dfa-42d314109dcf.png)
